### ISSUE TITLE
JS Error: Uncaught ReferenceError: _sqzl is not defined

### ISSUE THREAD

**Issue by xpoback** [squeezely/magento2-hyva-plugin#2]
Many pages have this error on load when called:

```
page-9-2021:649 Uncaught ReferenceError: _sqzl is not defined
    at Object.init (page-9-2021:649:32)
    at page-9-2021:642:50
```

The reason seems to be the following: [in line 29 in `default.phtml`](https://github.com/squeezely/magento2-hyva-plugin/blob/main/src/view/frontend/templates/default.phtml#L29)  variable `_sqlz` is _undeclared_ anywhere before the assignment:

```JS
window._sqzl = _sqzl || [];
```

An additional check whether the variable has been declared might help avoid the error:
```JS
window._sqzl = (typeof _sqzl !== 'undefined' && _sqzl) ? _sqzl : []; 
```

**Comment by Frank-Magmodules** [comment]
Hello @xpoback, it appears that we're unable to replicate this issue in our environment. 
Could you please reach out to us [directly](https://www.magmodules.eu/help)? We'd like to work with you to investigate and address the issue.

**Comment by Frank-Magmodules** [comment]
Hello @xpoback, I'm delighted to inform you that we've recently rolled out an [update](https://github.com/squeezely/magento2-hyva-plugin/releases.) addressing the issue you mentioned. Thank you for providing your feedback. I'm closing this issue for now, but please don't hesitate to reach out or reopen it if you have any further questions.
